-- drop table if exists databasechangelog;
-- drop table if exists databasechangeloglock;
--
-- drop table if exists build;
-- drop table if exists app;
-- drop table if exists project;
-- drop table if exists configuration;
-- drop table if exists language_builder;
-- drop table if exists builder;
-- drop table if exists language;
